export const adminMessage = {
  ADMIN_CREATED: 'Admin created successfully',
  ADMIN_ALREADY_EXISTS: 'Admin already exists',
  ADMIN_FETCHED: 'Admin fetched successfully',
  ADMIN_NOT_FOUND: 'Admin not found',
  ADMIN_UPDATED: 'Admin updated successfully',
  ADMIN_DELETED: 'Admin deleted successfully',
  ADMIN_LOGIN_SUCCESS: 'Admin login successfully',
  ADMIN_LOGOUT_SUCCESS: 'Admin logout successfully',
  INVALID_CREDENTIALS: 'Incorrect email or password',
  ADMIN_EMAIL_OR_MOBILE_ALREADY_EXISTS: 'Email or mobile number already exists',
  INVALID_CURRENT_PASSWORD: 'Incorrect current password',
  PASSWORD_CHANGED_SUCCESSFULLY: 'Password changed successfully',
  TOKEN_REFRESHED: 'Token refreshed successfully',
};
